// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package blockchain

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/entropyio/go-entropy/common"
	"github.com/entropyio/go-entropy/common/hexutil"
	"github.com/entropyio/go-entropy/common/mathutil"
	"github.com/entropyio/go-entropy/config"
)

var _ = (*genesisSpecMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (genesis Genesis) MarshalJSON() ([]byte, error) {
	type Genesis struct {
		Config     *config.ChainConfig                         `json:"config"`
		Nonce      mathutil.HexOrDecimal64                     `json:"nonce"`
		Timestamp  mathutil.HexOrDecimal64                     `json:"timestamp"`
		ExtraData  hexutil.Bytes                               `json:"extraData"`
		GasLimit   mathutil.HexOrDecimal64                     `json:"gasLimit"   gencodec:"required"`
		Difficulty *mathutil.HexOrDecimal256                   `json:"difficulty" gencodec:"required"`
		Mixhash    common.Hash                                 `json:"mixHash"`
		Coinbase   common.Address                              `json:"coinbase"`
		Alloc      map[common.UnprefixedAddress]GenesisAccount `json:"alloc"      gencodec:"required"`
		Number     mathutil.HexOrDecimal64                     `json:"number"`
		GasUsed    mathutil.HexOrDecimal64                     `json:"gasUsed"`
		ParentHash common.Hash                                 `json:"parentHash"`
		BaseFee    *mathutil.HexOrDecimal256                   `json:"baseFeePerGas"`
	}
	var enc Genesis
	enc.Config = genesis.Config
	enc.Nonce = mathutil.HexOrDecimal64(genesis.Nonce)
	enc.Timestamp = mathutil.HexOrDecimal64(genesis.Timestamp)
	enc.ExtraData = genesis.ExtraData
	enc.GasLimit = mathutil.HexOrDecimal64(genesis.GasLimit)
	enc.Difficulty = (*mathutil.HexOrDecimal256)(genesis.Difficulty)
	enc.Mixhash = genesis.Mixhash
	enc.Coinbase = genesis.Coinbase
	if genesis.Alloc != nil {
		enc.Alloc = make(map[common.UnprefixedAddress]GenesisAccount, len(genesis.Alloc))
		for k, v := range genesis.Alloc {
			enc.Alloc[common.UnprefixedAddress(k)] = v
		}
	}
	enc.Number = mathutil.HexOrDecimal64(genesis.Number)
	enc.GasUsed = mathutil.HexOrDecimal64(genesis.GasUsed)
	enc.ParentHash = genesis.ParentHash
	enc.BaseFee = (*mathutil.HexOrDecimal256)(genesis.BaseFee)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (genesis *Genesis) UnmarshalJSON(input []byte) error {
	type Genesis struct {
		Config     *config.ChainConfig                         `json:"config"`
		Nonce      *mathutil.HexOrDecimal64                    `json:"nonce"`
		Timestamp  *mathutil.HexOrDecimal64                    `json:"timestamp"`
		ExtraData  *hexutil.Bytes                              `json:"extraData"`
		GasLimit   *mathutil.HexOrDecimal64                    `json:"gasLimit"   gencodec:"required"`
		Difficulty *mathutil.HexOrDecimal256                   `json:"difficulty" gencodec:"required"`
		Mixhash    *common.Hash                                `json:"mixHash"`
		Coinbase   *common.Address                             `json:"coinbase"`
		Alloc      map[common.UnprefixedAddress]GenesisAccount `json:"alloc"      gencodec:"required"`
		Number     *mathutil.HexOrDecimal64                    `json:"number"`
		GasUsed    *mathutil.HexOrDecimal64                    `json:"gasUsed"`
		ParentHash *common.Hash                                `json:"parentHash"`
		BaseFee    *mathutil.HexOrDecimal256                   `json:"baseFeePerGas"`
	}
	var dec Genesis
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Config != nil {
		genesis.Config = dec.Config
	}
	if dec.Nonce != nil {
		genesis.Nonce = uint64(*dec.Nonce)
	}
	if dec.Timestamp != nil {
		genesis.Timestamp = uint64(*dec.Timestamp)
	}
	if dec.ExtraData != nil {
		genesis.ExtraData = *dec.ExtraData
	}
	if dec.GasLimit == nil {
		return errors.New("missing required field 'gasLimit' for Genesis")
	}
	genesis.GasLimit = uint64(*dec.GasLimit)
	if dec.Difficulty == nil {
		return errors.New("missing required field 'difficulty' for Genesis")
	}
	genesis.Difficulty = (*big.Int)(dec.Difficulty)
	if dec.Mixhash != nil {
		genesis.Mixhash = *dec.Mixhash
	}
	if dec.Coinbase != nil {
		genesis.Coinbase = *dec.Coinbase
	}
	if dec.Alloc == nil {
		return errors.New("missing required field 'alloc' for Genesis")
	}
	genesis.Alloc = make(GenesisAlloc, len(dec.Alloc))
	for k, v := range dec.Alloc {
		genesis.Alloc[common.Address(k)] = v
	}
	if dec.Number != nil {
		genesis.Number = uint64(*dec.Number)
	}
	if dec.GasUsed != nil {
		genesis.GasUsed = uint64(*dec.GasUsed)
	}
	if dec.ParentHash != nil {
		genesis.ParentHash = *dec.ParentHash
	}
	if dec.BaseFee != nil {
		genesis.BaseFee = (*big.Int)(dec.BaseFee)
	}
	return nil
}
